//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PandaUnityTest
{
    [Serializable]
    public class PlannerServiceRequest : Message
    {
        public const string k_RosMessageName = "panda_unity_test/PlannerService";
        public override string RosMessageName => k_RosMessageName;

        public ArmJointsMsg joints;
        public string routine;
        public Geometry.PoseMsg pick_pose;
        public Geometry.PoseMsg place_pose;

        public PlannerServiceRequest()
        {
            this.joints = new ArmJointsMsg();
            this.routine = "";
            this.pick_pose = new Geometry.PoseMsg();
            this.place_pose = new Geometry.PoseMsg();
        }

        public PlannerServiceRequest(ArmJointsMsg joints, string routine, Geometry.PoseMsg pick_pose, Geometry.PoseMsg place_pose)
        {
            this.joints = joints;
            this.routine = routine;
            this.pick_pose = pick_pose;
            this.place_pose = place_pose;
        }

        public static PlannerServiceRequest Deserialize(MessageDeserializer deserializer) => new PlannerServiceRequest(deserializer);

        private PlannerServiceRequest(MessageDeserializer deserializer)
        {
            this.joints = ArmJointsMsg.Deserialize(deserializer);
            deserializer.Read(out this.routine);
            this.pick_pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.place_pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joints);
            serializer.Write(this.routine);
            serializer.Write(this.pick_pose);
            serializer.Write(this.place_pose);
        }

        public override string ToString()
        {
            return "PlannerServiceRequest: " +
            "\njoints: " + joints.ToString() +
            "\nroutine: " + routine.ToString() +
            "\npick_pose: " + pick_pose.ToString() +
            "\nplace_pose: " + place_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
