//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PandaUnityTest
{
    [Serializable]
    public class PlannerServiceResponse : Message
    {
        public const string k_RosMessageName = "panda_unity_test/PlannerService";
        public override string RosMessageName => k_RosMessageName;

        public ArmTrajectoryMsg arm_trajectory;

        public PlannerServiceResponse()
        {
            this.arm_trajectory = new ArmTrajectoryMsg();
        }

        public PlannerServiceResponse(ArmTrajectoryMsg arm_trajectory)
        {
            this.arm_trajectory = arm_trajectory;
        }

        public static PlannerServiceResponse Deserialize(MessageDeserializer deserializer) => new PlannerServiceResponse(deserializer);

        private PlannerServiceResponse(MessageDeserializer deserializer)
        {
            this.arm_trajectory = ArmTrajectoryMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.arm_trajectory);
        }

        public override string ToString()
        {
            return "PlannerServiceResponse: " +
            "\narm_trajectory: " + arm_trajectory.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
