//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BaxterUnityTest
{
    [Serializable]
    public class NextActionMsg : Message
    {
        public const string k_RosMessageName = "baxter_unity_test/NextAction";
        public override string RosMessageName => k_RosMessageName;

        public string op;
        public int id;

        public NextActionMsg()
        {
            this.op = "";
            this.id = 0;
        }

        public NextActionMsg(string op, int id)
        {
            this.op = op;
            this.id = id;
        }

        public static NextActionMsg Deserialize(MessageDeserializer deserializer) => new NextActionMsg(deserializer);

        private NextActionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.op);
            deserializer.Read(out this.id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.op);
            serializer.Write(this.id);
        }

        public override string ToString()
        {
            return "NextActionMsg: " +
            "\nop: " + op.ToString() +
            "\nid: " + id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
