//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BaxterUnityTest
{
    [Serializable]
    public class PlannedTrajectoryMsg : Message
    {
        public const string k_RosMessageName = "baxter_unity_test/PlannedTrajectory";
        public override string RosMessageName => k_RosMessageName;

        public string arm;
        public Moveit.RobotTrajectoryMsg[] trajectory;

        public PlannedTrajectoryMsg()
        {
            this.arm = "";
            this.trajectory = new Moveit.RobotTrajectoryMsg[0];
        }

        public PlannedTrajectoryMsg(string arm, Moveit.RobotTrajectoryMsg[] trajectory)
        {
            this.arm = arm;
            this.trajectory = trajectory;
        }

        public static PlannedTrajectoryMsg Deserialize(MessageDeserializer deserializer) => new PlannedTrajectoryMsg(deserializer);

        private PlannedTrajectoryMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.arm);
            deserializer.Read(out this.trajectory, Moveit.RobotTrajectoryMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.arm);
            serializer.WriteLength(this.trajectory);
            serializer.Write(this.trajectory);
        }

        public override string ToString()
        {
            return "PlannedTrajectoryMsg: " +
            "\narm: " + arm.ToString() +
            "\ntrajectory: " + System.String.Join(", ", trajectory.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
