//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BaxterUnity
{
    [Serializable]
    public class ArmJointsMsg : Message
    {
        public const string k_RosMessageName = "baxter_unity/ArmJoints";
        public override string RosMessageName => k_RosMessageName;

        public double[] angles;

        public ArmJointsMsg()
        {
            this.angles = new double[0];
        }

        public ArmJointsMsg(double[] angles)
        {
            this.angles = angles;
        }

        public static ArmJointsMsg Deserialize(MessageDeserializer deserializer) => new ArmJointsMsg(deserializer);

        private ArmJointsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.angles, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.angles);
            serializer.Write(this.angles);
        }

        public override string ToString()
        {
            return "ArmJointsMsg: " +
            "\nangles: " + System.String.Join(", ", angles.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
