//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BaxterUnity
{
    [Serializable]
    public class NextActionMsg : Message
    {
        public const string k_RosMessageName = "baxter_unity/NextAction";
        public override string RosMessageName => k_RosMessageName;

        public string[] op;
        public int[] id;

        public NextActionMsg()
        {
            this.op = new string[0];
            this.id = new int[0];
        }

        public NextActionMsg(string[] op, int[] id)
        {
            this.op = op;
            this.id = id;
        }

        public static NextActionMsg Deserialize(MessageDeserializer deserializer) => new NextActionMsg(deserializer);

        private NextActionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.op, deserializer.ReadLength());
            deserializer.Read(out this.id, sizeof(int), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.op);
            serializer.Write(this.op);
            serializer.WriteLength(this.id);
            serializer.Write(this.id);
        }

        public override string ToString()
        {
            return "NextActionMsg: " +
            "\nop: " + System.String.Join(", ", op.ToList()) +
            "\nid: " + System.String.Join(", ", id.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
