//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BaxterUnity
{
    [Serializable]
    public class PlannedActionMsg : Message
    {
        public const string k_RosMessageName = "baxter_unity/PlannedAction";
        public override string RosMessageName => k_RosMessageName;

        public string action;
        public PlannedTrajectoryMsg arm_trajectory;

        public PlannedActionMsg()
        {
            this.action = "";
            this.arm_trajectory = new PlannedTrajectoryMsg();
        }

        public PlannedActionMsg(string action, PlannedTrajectoryMsg arm_trajectory)
        {
            this.action = action;
            this.arm_trajectory = arm_trajectory;
        }

        public static PlannedActionMsg Deserialize(MessageDeserializer deserializer) => new PlannedActionMsg(deserializer);

        private PlannedActionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.action);
            this.arm_trajectory = PlannedTrajectoryMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.action);
            serializer.Write(this.arm_trajectory);
        }

        public override string ToString()
        {
            return "PlannedActionMsg: " +
            "\naction: " + action.ToString() +
            "\narm_trajectory: " + arm_trajectory.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
