//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.PandaUnity
{
    public class PlannerServiceRequest : Message
    {
        public const string RosMessageName = "panda_unity/PlannerService";

        public ArmJoints joints;
        public string routine;
        public Geometry.Pose pick_pose;
        public Geometry.Pose place_pose;

        public PlannerServiceRequest()
        {
            this.joints = new ArmJoints();
            this.routine = "";
            this.pick_pose = new Geometry.Pose();
            this.place_pose = new Geometry.Pose();
        }

        public PlannerServiceRequest(ArmJoints joints, string routine, Geometry.Pose pick_pose, Geometry.Pose place_pose)
        {
            this.joints = joints;
            this.routine = routine;
            this.pick_pose = pick_pose;
            this.place_pose = place_pose;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(joints.SerializationStatements());
            listOfSerializations.Add(SerializeString(this.routine));
            listOfSerializations.AddRange(pick_pose.SerializationStatements());
            listOfSerializations.AddRange(place_pose.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.joints.Deserialize(data, offset);
            var routineStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.routine = DeserializeString(data, offset, routineStringBytesLength);
            offset += routineStringBytesLength;
            offset = this.pick_pose.Deserialize(data, offset);
            offset = this.place_pose.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "PlannerServiceRequest: " +
            "\njoints: " + joints.ToString() +
            "\nroutine: " + routine.ToString() +
            "\npick_pose: " + pick_pose.ToString() +
            "\nplace_pose: " + place_pose.ToString();
        }
    }
}
