//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BaxterUnityTest
{
    [Serializable]
    public class ActionServiceResponse : Message
    {
        public const string k_RosMessageName = "baxter_unity_test/ActionService";
        public override string RosMessageName => k_RosMessageName;

        public PlannedTrajectoryMsg arm_trajectory;

        public ActionServiceResponse()
        {
            this.arm_trajectory = new PlannedTrajectoryMsg();
        }

        public ActionServiceResponse(PlannedTrajectoryMsg arm_trajectory)
        {
            this.arm_trajectory = arm_trajectory;
        }

        public static ActionServiceResponse Deserialize(MessageDeserializer deserializer) => new ActionServiceResponse(deserializer);

        private ActionServiceResponse(MessageDeserializer deserializer)
        {
            this.arm_trajectory = PlannedTrajectoryMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.arm_trajectory);
        }

        public override string ToString()
        {
            return "ActionServiceResponse: " +
            "\narm_trajectory: " + arm_trajectory.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
