//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BaxterUnityTest
{
    [Serializable]
    public class JointStateServiceResponse : Message
    {
        public const string k_RosMessageName = "baxter_unity_test/JointStateService";
        public override string RosMessageName => k_RosMessageName;

        public Sensor.JointStateMsg joint_state_msg;

        public JointStateServiceResponse()
        {
            this.joint_state_msg = new Sensor.JointStateMsg();
        }

        public JointStateServiceResponse(Sensor.JointStateMsg joint_state_msg)
        {
            this.joint_state_msg = joint_state_msg;
        }

        public static JointStateServiceResponse Deserialize(MessageDeserializer deserializer) => new JointStateServiceResponse(deserializer);

        private JointStateServiceResponse(MessageDeserializer deserializer)
        {
            this.joint_state_msg = Sensor.JointStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joint_state_msg);
        }

        public override string ToString()
        {
            return "JointStateServiceResponse: " +
            "\njoint_state_msg: " + joint_state_msg.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
