//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BaxterUnity
{
    [Serializable]
    public class ActionServiceResponse : Message
    {
        public const string k_RosMessageName = "baxter_unity/ActionService";
        public override string RosMessageName => k_RosMessageName;

        public int pick_seq;
        public int tool_seq;
        public string action;
        public PlannedTrajectoryMsg arm_trajectory;

        public ActionServiceResponse()
        {
            this.pick_seq = 0;
            this.tool_seq = 0;
            this.action = "";
            this.arm_trajectory = new PlannedTrajectoryMsg();
        }

        public ActionServiceResponse(int pick_seq, int tool_seq, string action, PlannedTrajectoryMsg arm_trajectory)
        {
            this.pick_seq = pick_seq;
            this.tool_seq = tool_seq;
            this.action = action;
            this.arm_trajectory = arm_trajectory;
        }

        public static ActionServiceResponse Deserialize(MessageDeserializer deserializer) => new ActionServiceResponse(deserializer);

        private ActionServiceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.pick_seq);
            deserializer.Read(out this.tool_seq);
            deserializer.Read(out this.action);
            this.arm_trajectory = PlannedTrajectoryMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pick_seq);
            serializer.Write(this.tool_seq);
            serializer.Write(this.action);
            serializer.Write(this.arm_trajectory);
        }

        public override string ToString()
        {
            return "ActionServiceResponse: " +
            "\npick_seq: " + pick_seq.ToString() +
            "\ntool_seq: " + tool_seq.ToString() +
            "\naction: " + action.ToString() +
            "\narm_trajectory: " + arm_trajectory.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
