//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BaxterUnity
{
    [Serializable]
    public class JointStateServiceRequest : Message
    {
        public const string k_RosMessageName = "baxter_unity/JointStateService";
        public override string RosMessageName => k_RosMessageName;

        public Std.StringMsg request;

        public JointStateServiceRequest()
        {
            this.request = new Std.StringMsg();
        }

        public JointStateServiceRequest(Std.StringMsg request)
        {
            this.request = request;
        }

        public static JointStateServiceRequest Deserialize(MessageDeserializer deserializer) => new JointStateServiceRequest(deserializer);

        private JointStateServiceRequest(MessageDeserializer deserializer)
        {
            this.request = Std.StringMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.request);
        }

        public override string ToString()
        {
            return "JointStateServiceRequest: " +
            "\nrequest: " + request.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
